train=[
    ("hi","greeting"),
    ("hi,how are you?","greeting"),
    ("howdy","greeting"),
    ("hello","greeting"),
    ("how are you doing?","greeting"),
    ("hope you are well","greeting"),
    ("Hey man","greeting"),
    ("How are things","greeting"),
    ("How’s everything","greeting"),
    ("How’s life","greeting"),
    ("Nice to see you","greeting"),
    ("Good to see you","greeting"),
    ("It’s nice to meet you ","greeting"),
    ("Pleased to meet you","greeting"),
    ("How do you do?","greeting"),
    ("How have you been?","greeting"),
    ("goodmorning?","greeting"),
    ("goodevening?","greeting"),
    ("goodnight?","greeting"),
    ("hiya","greeting"),
    ("hello, mam","greeting"),
    ("goodafternoon, how are you?","greeting"),
   
    ("what's the weather","wquery"),
    ("what's the weather like?","wquery"),
    ("tell me about the weather","wquery"),
    ("weather?","wquery"),
    ("weather like?","wquery"),
    ("how is the weather outside?","wquery"),
    ("what's the weather today","wquery"),
    ("what's the weather like right now?","wquery"),
    ("tell me about weather outside right now","wquery"),
    ("more about weather?","wquery"),
    ("weather please","wquery"),
    ("weather like right now","wquery"),
    ("what's the weather today","wquery"),
    ("more about weather","wquery"),
    ("tell me about weather this instant","wquery"),
    ("weather query","wquery"),
    ("hi tell me about weather today","wquery"),
    ("hey what's the weather like","wquery"),
    
    ("what's the traffic","tquery"),
    ("traffic in any city","tquery"),
    ("traffic?","tquery"),
    ("how bad is the traffic","tquery"),
    ("traffic in delhi","tquery"),
    ("delhi traffic","tquery"),
    ("traffic query","tquery"),
    
    ("send an email","mail"),
    ("email","mail"),
    ("open email","mail"),
    ("email?","mail"),
    ("email query","mail"),
    ("i want to write an email","mail"),
    ("any new email?","mail"),
    ("launch email","mail"),
    ("email?","mail"),
    ("i want to send an email query","mail"),
    ("i want to send an email","mail"),
    ("hi, i want to send an email","mail"),
    ("what's my mail","mail"),
    ("email?","mail"),
    ("hi, i want to write an email","mail"),
    
    ("what is the time?","time"),
    ("time?","time"),
    ("time right now?","time"),
    ("what is the time,right now?","time"),
    ("tell me the time?","time"),
    ("show me the time?","time"),
    ("please tell me the time?","time"),
    ("what time is it?","time"),
    ("present time?","time"),
    ("tell me the present time?","time"),
    ("time as of now?","time"),
    
    ("play some song on YouTube","yt"),
    ("play something on YouTube","yt"),
    ("play YouTube","yt"),
    ("launch YouTube","yt"),
    ("YouTube","yt"),
    ("open YouTube","yt"),
    ("i want to listen something on YouTube","yt"),
    ("YouTube please","yt"),
    ("open the video on YouTube","yt"),
    ("start playing a song or video YouTube","yt"),
    ("search for a song or video on YouTube","yt"),
    ("find a song or video on YouTube","yt"),
    ("turn up a song or video on YouTube","yt"),
    ("tune in a song or video on YouTube","yt"),
    ("Youtube please","yt"),
    ("open the video on YouTube","yt"),
    ("start playing a song or video YouTube","yt"),
    ("search for a song or video on YouTube","yt"),
    ("find a song or video on YouTube","yt"),
    ("turn up a song or video on YouTube","yt"),
    ("tune in a song or video on YouTube","yt"),
    ("hey open the video on YouTube","yt"),
    ("hi start playing a song or video YouTube","yt"),
    ("howdy, search for a song or video on YouTube","yt"),
    ("hello, find a song or video on YouTube","yt"),
    ("hi, turn up a song or video on YouTube","yt"),
    ("YouTube baby","yt"),
    ("hey launch YouTube for me","yt"),
    ("tune in a song or video on YouTube","yt"),
    ("hey open the video on YouTube","yt"),
    ("hi start playing a song or video YouTube","yt"),
    ("howdy, search for a song or video on YouTube","yt"),
    ("hello, find a song or video on YouTube","yt"),
    ("hi, turn up a song or video on YouTube","yt"),
    ("YouTube for me ","yt"),
    
    ("launch Google","google"),
    ("open Google","google"),
    ("Google","google"),
    ("Google please","google"),
    ("search on Google","google"),
    ("find on Google","google"),
    ("Google query","google"),
    ("Google me something please","google"),
    ("Google","google"),
    ("i want to search something on Google","google"),
    ("Google me something","google"),
    ("i want to Google","google"),
    ("i want to use Google","google"),
    ("hi open Google please","google"),
    ("hello, launch Google please","google"),
    ("hi,i want to Google something","google"),
    ("i want to search something on Google","google"),
    ("launch Google","google"),
    ("open Google","google"),
    ("Google please","google"),
    ("play Google","google"),
    
    ("Corona virus","covid"),
    ("what are the stats of Corona virus","covid"),
    ("about Corona virus","covid"),
    ("stats on Corona virus","covid"),
    ("total number of Corona virus patients","covid"),
    ("world statistics on Corona virus","covid"),
    ("Corona virus Patients","covid"),
    ("Corona","covid"),
    ("Corona virus pandemic","covid"),
    ("what are the statistics of Corona virus patients","covid"),
    ("Number of people suffering from Corona virus","covid"),
    ("number of people in the world suffering from coronavirus","covid"),
    ("world stats on coronavirus","covid"),
    ("details on coronavirus","covid"),
    ("coronavirus infected people from a country","covid"),
    ("number on coronavirus patients","covid"),
    ("coronavirus patients","covid"),
    ("coronavirus infected patients","covid"),
    ("world on coronavirus patients","covid"),
    ("tell me about coronavirus stats or patient numbers","covid"),
    ("coronavirus pandemic","covid"),
    
    ("recommend me a good movie ","movie"),
    ("recommend me a movie","movie"),
    ("tell me about a good movie to watch","movie"),
    ("movie please","movie"),
    ("movies","movie"),
    ("show me some good movies to watch","movie"),
    ("recommend or show me some movies","movie"),
    ("suggest me some good movie or movies","movie"),
    ("best movie to watch","movie"),
    ("top movie or movies to watch","movie"),
    ("help me with a movie or movies","movie"),
    ("hi recommend me a good movie or movies","movie"),
    ("hey suggest me a good movie or movies","movie"),
    ("show me good movie or movies","movie"),
    ("movie or movies please","movie"),
    ("recommendation of movie or movies","movie"),
    ("i am too bored, recommend me a good movie or movies","movie"),
    ("recommend me something to watch","movie"),
    ("suggest me something good to watch","movie"),
    ("i want to watch a good movie or movies","movie"),
    ("i need to watch a good movie or movies help me","movie"),
    
    ("tell me the news today","news"),
    ("what's the news of the day","news"),
    ("news","news"),
    ("news please","news"),
    ("share the news with me","news"),
    ("what are the news headlines","news"),
    ("headlines of the day","news"),
    ("i want to know the news of the day","news"),
    ("current news","news"),
    ("read me the headlines or news","news"),
    ("read me the highlights of the day","news"),
    ("give me the news or headlines or highlights","news"),
    ("latest news or headlines or highlights","news"),
    ("inform me about the lastest news or headlines or highlights ","news"),
    ("tell me about upcoming news or headlines","news"),
    ("current headlines","news"),
    ("hey give me the news or headlines","news"),
    ("news or headlines right now","news"),
    ("what is the highlights or headlines of the day","news"),
    ("news right now","news"),
    ("help me with the news","news"),
     
    ("open maps","events"),
    ("events near me","events"),
    ("things around me","events"),
    ("near me events in maps","events"),
    ("open events near me in maps","events"),
    ("what is happening around me","events"),
    ("things happening around me","events"),
    ("things available around me","events"),
    ("maps","events"),
    ("find me something on maps","events"),
    ("hey find me something on maps or events around me","events"),
    ("events happening around me on maps","events"),
    ("events around me","news"),
    ("things or events around or near me","events"),
    ("what all is available around me","events"),
    ("available around me in maps","events"),
    ("hey find things or events available around me","events"),
    ("available things or events happening around me","events"),
    ("open maps and show things or events available around me","events"),
    ("things or events available or happening right now","events"),
    ("help me with things available or events happening around or near me","events"),
    ("iopen maps and available around me in maps","events"),
    ("hey find things or events available around me in maps or map","events"),
    ("available things or events happening around me","events"),
    ("open maps and show things or events available around me","events"),
    ("things or events available or happening right now in maps","events"),
    ("help me with things available or events happening around or near me in maps please","events"),
    
    
    ("launch Instagram ","insta"),
    ("open Instagram","insta"),
    ("Instagram","insta"),
    ("Instagram please","insta"),
    ("i want to open Instagram","insta"),
    ("open Instagram for me","insta"),
    ("Instagram query","insta"),
    ("Instagram site please","insta"),
    ("use Instagram to find a page or a person","insta"),
    ("i want to search something on Instagram","insta"),
    ("Instagram me something","insta"),
    ("i want to Instagram","insta"),
    ("i want to use Instagram","insta"),
    ("hi open Instagram please","insta"),
    ("hello, launch Instagram please","insta"),
    ("hi,i want to Instagram something","insta"),
    ("i want to search something on Instagram","insta"),
    ("launch Instagram and search a page","insta"),
    ("open Instagram and find me my query","insta"),
    ("search something or someone on Instagram ","insta"),
    ("play Instagram","insta"),
    
    ("launch Facebook please ","fb"),
    ("open Facebook","fb"),
    ("Facebook app right now","fb"),
    ("Facebook please","fb"),
    ("i want to open Facebook","fb"),
    ("open Facebook for me","fb"),
    ("Facebook query","fb"),
    ("Facebook site please","fb"),
    ("use Facebook to find a page or a person","fb"),
    ("i want to search something on Facebook right now","fb"),
    ("Facebook me something","fb"),
    ("i want to Facebook","fb"),
    ("i want to use Facebook","fb"),
    ("hi open Facebook please","fb"),
    ("hello, launch Facebook please","fb"),
    ("hi,i want to Facebook something","fb"),
    ("i want to search something on Facebook","fb"),
    ("launch Facebook and search a page","fb"),
    ("open Facebook and find me my query","fb"),
    ("search something or someone on Facebook ","fb"),
    ("play Facebook fast","fb"),
    ("Facebook","fb"),
    
    ("launch translator please ","translate"),
    ("open translator","translate"),
    ("translator app right now","translate"),
    ("translator please","translate"),
    ("i want to open translator","translate"),
    ("open translator for me","translate"),
    ("translator query","translate"),
    ("i want to translate something","translate"),
    ("translate something for me","translate"),
    ("translate a language for me please","translate"),
    ("translate something for me","translate"),
    ("i want to translator","translate"),
    ("i want to use translator","translate"),
    ("hi open translator please","translate"),
    ("hello, launch translator please","translate"),
    ("hi,i want to translate something","translate"),
    ("i want to search a language on translator","translate"),
    ("launch translator and translate a language","translate"),
    ("open translator and translate","translate"),
    ("translate a language for me ","translate"),
    ("translate for me","translate"),
    ("translator","translate"),
    
    ("launch BookMyShow please ","bms"),
    ("open BookMyShow","bms"),
    ("BookMyShow app right now","bms"),
    ("BookMyShow please","bms"),
    ("i want to open BookMyShow","bms"),
    ("open BookMyShow for me","bms"),
    ("BookMyShow query","bms"),
    ("i want to find latest events or movies on BookMyShow","bms"),
    ("open BookMyShow for movies or events happening right now","bms"),
    ("BookMyShow to search for events or movies","bms"),
    ("BookMyShow","bms"),
    ("i want to go for BookMyShow","bms"),
    ("i want to use BookMyShow","bms"),
    ("hi open bookmyshow please","bms"),
    ("hello, launch bookmyshow please","bms"),
    ("hi,i want to bookmyshow","bms"),
    ("i want to search for soemthing interesting on bookmyshow","bms"),
    ("i want to book a show on bookmyshow","bms"),
    ("open bookmyshow and suggest me something a event or a movie ","bms"),
    ("bookmyshow for me","bms"),
    ("bookmyshow and suggest me something","bms"),
    
    ("please launch Zomato","zomato"),
    ("open Zomato","zomato"),
    ("Zomato app right now","zomato"),
    ("Zomato please","zomato"),
    ("i want to open Zomato","zomato"),
    ("open Zomato for me","zomato"),
    ("Zomato query","zomato"),
    ("i want to find food on Zomato","zomato"),
    ("open Zomato and search for food right now","zomato"),
    ("launch Zomato to search for food","zomato"),
    ("Zomato","zomato"),
    ("i want to go for Zomato","zomato"),
    ("i want to use Zomato","zomato"),
    ("hi open Zomato please","zomato"),
    ("hello, launch Zomato please","zomato"),
    ("hi,i want you to open Zomato","zomato"),
    ("i want to search for some food on Zomato","zomato"),
    ("i want food around me on Zomato","zomato"),
    ("open Zomato and suggest me something to eat ","zomato"),
    ("Zomato for me","zomato"),
    ("Zomato and suggest me something to eat","zomato"),
    
    ("please launch WhatsApp","whatsapp"),
    ("open WhatsApp","whatsapp"),
    ("WhatsApp webapp right now","whatsapp"),
    ("WhatsApp please sofi","whatsapp"),
    ("i want to open WhatsApp","whatsapp"),
    ("open WhatsApp for me","whatsapp"),
    ("WhatsApp query","whatsapp"),
    ("i want to send a message on WhatsApp","whatsapp"),
    ("open WhatsApp and send a message for me right now","whatsapp"),
    ("launch WhatsApp to search for a contact or send a message","whatsapp"),
    ("WhatsApp","whatsapp"),
    ("i want to go for WhatsApp webapp","whatsapp"),
    ("i want to use WhatsApp","whatsapp"),
    ("hi open WhatsApp please","whatsapp"),
    ("hello, launch WhatsApp please and send a message to a contact","whatsapp"),
    ("hi,i want you to open WhatsApp and search for a contact","whatsapp"),
    ("i want to send a message to someone on WhatsApp","whatsapp"),
    ("i want a contact of someone on WhatsApp","whatsapp"),
    ("open WhatsApp and find me a contact number ","whatsapp"),
    ("WhatsApp for me","whatsapp"),
    ("WhatsApp and find or send","whatsapp")
    
  
    
    ]
    
    














